dataset: ['utkface', 'cifar', 'tiny-imagenet']
model: ['small_cnn', 'resnet9', 'resnet18']
epochs: [2]
lr: [0.01] 
iid: [0]
num_users: [4]
frac: [0.5]
local_ep: [2]
local_bs: [128]
q: [0.1] #qfedavg,
fl_method: ['FedProx', 'qFedAvg', 'FedSyn']
mu: [0.01]
sparsification_ratio: [0.5] #fedsyn
sparsification_type: ['rtopk'] #fedsyn
dist_noniid: [0.8]
use_fair_sparsification: [0, 1] #fedsyn
seed: [1234]
